flomesh-io/fsm-classic

.github/workflows/release.yml

Support sign container images with cosign, it only affects release workflow.

Support sign container images with cosign 

---

etc/cluster1.yaml
etc/cluster2.yaml
etc/control-plane.yaml

add host alias to k3d config file and bind to external IP of host machine, this's for development.

add host alias to k3d config file 

---

charts/fsm/Chart.yaml
charts/fsm/templates/_helpers.tpl
charts/fsm/templates/ingress-pipy-deployment.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml

fix: chart values of ingress resource quota

---

charts/fsm/components/scripts/ingress/plugins/logger.js

Get logger url and authorization token from environment variables.

[fix] Get logger url and authorization token from environment variables.

---

charts/namespaced-ingress/templates/deployment.yaml
charts/namespaced-ingress/templates/role.yaml
charts/namespaced-ingress/templates/rolebinding.yaml
charts/namespaced-ingress/templates/service.yaml
charts/namespaced-ingress/templates/serviceaccount.yaml
controllers/namespacedingress/v1alpha1/namespacedingress_controller.go

refactor: move values of namespaced ingress under field ngis

---

apis/namespacedingress/v1alpha1/namespacedingress_types.go
charts/fsm/crds/flomesh.io_namespacedingresses.yaml
charts/namespaced-ingress/templates/deployment.yaml
samples/ingress/102-namespaced-ingress-w-env-n-anno.yaml

feature: setting log level for namespaced ingress

---

cmd/bootstrap/main.go

refactor: simplify the code of updating SSL passthrough config

---

apis/namespacedingress/v1alpha1/namespacedingress_types.go
apis/namespacedingress/v1alpha1/zz_generated.deepcopy.go
charts/fsm/crds/flomesh.io_namespacedingresses.yaml
charts/namespaced-ingress/templates/deployment.yaml
samples/ingress/102-namespaced-ingress-w-env-n-anno.yaml

feat: add pod annotations to NamespacedIngress CRD

---

charts/fsm/templates/ingress-pipy-deployment.yaml
charts/fsm/templates/ingress-pipy-service.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
charts/namespaced-ingress/templates/deployment.yaml
charts/namespaced-ingress/templates/service.yaml
deploy/fsm-dev.yaml
deploy/fsm.yaml

refactor: restructure values.yaml

---

.github/workflows/devel.yml
.github/workflows/release.yml

ci: specify helm version

---

apis/namespacedingress/v1alpha1/namespacedingress_types.go
charts/fsm/crds/flomesh.io_namespacedingresses.yaml

fix: set defaults for SSL passthrough

---

charts/fsm/templates/fsm-role.yaml
charts/fsm/templates/mesh-config-configmap.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
charts/tpls/templates/_images.tpl
cmd/manager/main.go
controllers/proxyprofile/v1alpha1/proxyprofile_controller.go
controllers/servicelb/node_controller.go
controllers/servicelb/service_controller.go
controllers/servicelb/types.go
deploy/fsm-dev.yaml
deploy/fsm.yaml
etc/control-plane.yaml
pkg/config/mesh.go
pkg/helm/helm.go
pkg/util/ctrl.go
pkg/util/slice.go
pkg/webhooks/cm/config_webhook.go

feat: support service-lb

---

charts/fsm/values.yaml

refactor: remove unused chart options

---

Makefile

ci: upgrade goreleaser

---

apis/globaltrafficpolicy/v1alpha1/types.go
cmd/manager/webhooks.go
pkg/webhooks/cluster/cluster_webhook.go
pkg/webhooks/cm/config_webhook.go
pkg/webhooks/defaulter.go
pkg/webhooks/gateway/gateway_webhook.go
pkg/webhooks/gatewayclass/gatewayclass_webhook.go
pkg/webhooks/globaltrafficpolicy/webhook.go
pkg/webhooks/httproute/httproute_webhook.go
pkg/webhooks/namespacedingress/namespacedingress_webhook.go
pkg/webhooks/proxyprofile/proxyprofile_webhook.go
pkg/webhooks/referencepolicy/referencepolicy_webhook.go
pkg/webhooks/serviceexport/webhook.go
pkg/webhooks/serviceimport/webhook.go
pkg/webhooks/tcproute/tcproute_webhook.go
pkg/webhooks/tlsroute/tlsroute_webhook.go
pkg/webhooks/types.go
pkg/webhooks/udproute/udproute_webhook.go
pkg/webhooks/validator.go

fix: support mutating and validating GlobalTrafficPolicy

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/devel.yml
.github/workflows/release-helm-chart.yml
.github/workflows/release.yml
.github/workflows/trivy.yml

feat: upgrade OS of GH action to Ubuntu 22.04

---

pkg/controller/ingress.go

fix: trigger ingress delete event

---

charts/fsm/templates/egress-gateway-configmap.yaml
charts/fsm/templates/egress-gateway-deployment.yaml
charts/fsm/templates/egress-gateway-service.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
charts/tpls/templates/_annotations.tpl
charts/tpls/templates/_labels.tpl

Support multiple forwarding modes for egress gateway.

Support multiple forwarding modes for egress gateway.

---

charts/fsm/templates/tests/test-ingress-pipy.yaml
charts/fsm/templates/tests/test-repo.yaml
charts/tpls/templates/_services.tpl

feat: helm chart tests

---

.github/workflows/build-pipy.yml

fix: wrong inputs argument name

---

.github/workflows/build-pipy.yml

fix: checkout code before building image

---

.github/pull_request_template.md

ci: add pull request template

---

pkg/cache/ingress.go
pkg/cache/local_cache.go

fix: configure multiple paths for same backend

---

charts/fsm/templates/ingress-pipy-service.yaml
charts/fsm/templates/mesh-config-configmap.yaml
charts/namespaced-ingress/templates/service.yaml
deploy/fsm-dev.yaml
deploy/fsm.yaml
pkg/config/listener.go
pkg/config/mesh.go

fix: update spec ingress-pipy svc upon TLS config changes

---

cmd/manager/eventhandlers.go
cmd/manager/main.go
pkg/config/handler.go
pkg/config/listener.go

fix: update ingress spec and mesh config if TLS is disabled/enabled

---

cmd/manager/webhooks.go
pkg/cache/ingress.go
pkg/commons/consts.go
pkg/util/ingress.go
pkg/webhooks/defaulter.go
pkg/webhooks/ingress/webhook.go
pkg/webhooks/register.go
pkg/webhooks/validator.go

feat: validate the existence of referenced secret of ingress

---

apis/globaltrafficpolicy/v1alpha1/types.go
apis/serviceexport/v1alpha1/serviceexport_types.go
apis/serviceimport/v1alpha1/serviceimport_types.go
charts/fsm/apis/flomesh.io_mcs-api.yaml
deploy/fsm-dev.yaml
deploy/fsm.yaml

feat: add short name for MCS APIs

---

controllers/flb/service_controller.go

feat: record FLB API error to k8s event

---

controllers/flb/service_controller.go

fix: annotations of service takes precedence over configuration from secret

---

controllers/flb/service_controller.go

fix: prepare settings before invoking FLB API

---

charts/fsm/templates/fsm-role.yaml
charts/fsm/templates/mesh-config-role.yaml
charts/namespaced-ingress/templates/rolebinding.yaml
controllers/namespacedingress/v1alpha1/namespacedingress_controller.go
deploy/fsm-dev.yaml
deploy/fsm.yaml
pkg/helm/helm.go

fix: NamespacedIngress has no enough permission to list deployments

---

charts/fsm/templates/flb-secret.yaml
charts/fsm/values.yaml
controllers/flb/service_controller.go
deploy/fsm-dev.yaml
pkg/commons/consts.go

feat: FLB supports multiple k8s cluster

---

controllers/flb/service_controller.go
deploy/fsm.yaml
samples/flb/values.yaml

feat: FLB supports service tags
-   Did you notify the maintainers …

feat: FLB supports service tags

---

controllers/flb/service_controller.go

fix: generate same key for create, update and delete LB

---

charts/fsm/templates/flb-secret.yaml
charts/fsm/values.yaml
controllers/flb/service_controller.go
deploy/fsm-dev.yaml
deploy/fsm.yaml
pkg/commons/consts.go
pkg/webhooks/flb/secret/webhook.go

refactor: remove unused cluster HTTP header and config
